few refactor and added comments
k8-proxy/k8-test-data pull request #27
Opened 2020-09-13 13:52 UTC by belwase

2020-09-15 19:46 UTC, susilupwork approved these changes
Please collaborate with @samarthdd  to get proper Minio service  and integrate.

2020-09-15 19:46 UTC, susilupwork commented on upwork-devs/ashish-belwase/virusshare_poc/src/file_service.py
> +    @staticmethod
The method is just getting extension and name of file, does not sound correct. Please get clarification on meta information expectation from @manish2kcoder  or @dinis-cruz-gw .

2020-09-17 09:09 UTC, susilupwork commented
Test File distribution API should be independent of other part of the code and should run in separate K8 pod. It will call Minio service to get the file and delivery to the requesting user. The code to be independent and isolated from Scrapping part.

2020-09-17 13:08 UTC, susilupwork requested changes
Distribution API code be separated completely, Now it is intermingled with POC scrapper code. Please take care of this.

2020-09-20 12:34 UTC, DinisCruz requested changes
108 files doesn’t look right, should all these files be here?

2020-09-20 12:38 UTC, merged