Scrapper implementated for multiple sites
k8-proxy/k8-test-data pull request #52
Opened 2020-09-25 12:03 UTC by samarthdd

Deliverables:
Scraping of multiple sites and configuration of the same from .env.
The following sites are covered:
https://virusshare.com/
https://github.com/ytisf/theZoo
http://www.tekdefense.com/downloads/malware-samples/
https://das-malwerk.herokuapp.com/

2. Storage
Storage using minio adapter.
Malware Zip files are uploaded to minio directly.

2020-09-26 22:16 UTC, DinisCruz commented
Please fix conflict

2020-09-27 21:22 UTC, samarthdd commented
> Please fix conflict



> Please fix conflict

Done.I have fixed conflict and commited the same

2020-09-27 21:25 UTC, susilupwork requested changes
- All Key must come from environment variable. use config.py to load them. 
- Virushare the scrapping constraint should be in config. 1 request per 15 sec. Also there should global scrapping should be for all sites , say 10 sec for each request. We do not want anybody gets down due to us.
- Do not use site name as MinIObucketname. You can use original zip or similar. 
- The MinIO client should call only the MinIO endpoint. The scrapper will only deal with MinIO end point, no direct calling. 
- Many places still Exception handling  is not there, add and log if exception occurs.
- Go through GW coding guideline . Many violations noticed in constant name and class name etc.

2020-09-27 21:25 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/src/pipelines.py
> +                if (info.spider.name == "virusshare"):
No hard code logic for virusshare. Generalize it.

2020-09-27 21:25 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/src/pipelines.py
> +            if not client.bucket_exists(bucket_name):
This should be minIO service code. It should be there not at the calling end.

2020-09-27 21:25 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/src/spiders/malshare_crawler.py
> +        'DUPEFILTER_CLASS': 'scrapy.dupefilters.BaseDupeFilter',
Should go to BaseScrapper.

2020-09-27 21:25 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/src/spiders/malshare_crawler.py
> +        yield scrapy.Request(url=self.base_url, callback=self.parser)
Add Exception handling and log if exception occurs

2020-09-27 21:25 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/storage/config/config.ini
> +HOSTNAME=Please provide Hostname
No key in config file. Only in .env file as sample.

2020-09-27 21:25 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/storage/src/minio_adapter.py
> +                                 access_key=config.get('AWS_ACCESS_KEY_ID'),
MiniIO is not going to store in AWS S3 directly.

2020-09-27 21:25 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/src/utils/minio_client.py
> +        try:
The MinIO client should call only the MinIO endpoint. The scrapper will only deal with MinIO end point, no direct calling.

2020-09-27 21:30 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/pipelines.py
> +            Downloads file
This is removed as you see the same in red highlight

2020-09-29 08:39 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/config/config.ini
> +vs_api_key=enter virus share api key here
Resolved in latest commit

2020-09-29 08:40 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/constants.py
> +download_path = BASE_DIR + "/static/"
Resolved in latest commit

2020-09-29 08:40 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/glasswall_crawler_runner.py
>  logging.basicConfig(filename="testdata.log",
Resolved

2020-09-29 08:41 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/pipelines.py
> +                if (info.spider.name == "virusshare"):
I have removed hard code logic and has implemented generalized logic

2020-09-29 08:41 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/pipelines.py
> +            if not client.bucket_exists(bucket_name):
Removed it and updated in latest commit

2020-09-29 08:41 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/spiders/malshare_crawler.py
> +        yield scrapy.Request(url=self.base_url, callback=self.parser)
Added exception handling for all methods

2020-09-29 08:41 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/storage/src/minio_adapter.py
> +                                 access_key=config.get('AWS_ACCESS_KEY_ID'),
Removed

2020-09-29 10:57 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/storage/config/config.ini
> +HOSTNAME=Please provide Hostname
removed keys in config

2020-09-29 12:04 UTC, susilupwork approved these changes
Please do this changes after 29th demo 

- DO not hard code values, It should come from config file. 
- Do not use sleep, instead use DOWNLOAD_DELAY. The default delay should be there for every site.
- No KEY in config file, take it to to environment variable

2020-09-29 12:04 UTC, susilupwork commented on storage/config/config.ini
> +HOSTNAME=Please provide Hostname
No KEY in config file, take it to to environment variable

2020-09-29 19:27 UTC, samarthdd commented on storage/config/config.ini
> +HOSTNAME=Please provide Hostname
Updated

2020-09-29 19:27 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/spiders/virus_share.py
> +                sleep(15)
Updated with download_dealy

2020-09-29 19:27 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/src/spiders/dasmalwerk_crawler.py
> +        try:
added info logging in scraper

2020-09-30 12:46 UTC, dtollaku approved these changes

2020-09-30 12:47 UTC, merged