#45: RabbitMQ client to publish file upload jobs to remote queue
k8-proxy/k8-test-data pull request #54
Opened 2020-09-25 17:09 UTC by virajut

- Added RabbitMQ client with minimum required configurations
- It puts a zip file along with path into a remote queue (Running on a different container)

Resolves: #45

2020-09-26 04:37 UTC, belwase commented on gw_crawler/malicious_file_crawler/src/pipelines.py
> +            payload = {"file": zipped_file}
In payload along with file, please also send the type of message.
for eg. ` {"type": "process_zip", "file": file_id}`

2020-09-26 04:38 UTC, belwase commented on gw_crawler/malicious_file_crawler/src/pipelines.py
> +            payload = {"file": zipped_file}
sending "zipped_file" won't work , because it is filepath of that file inside that container. you need to send  key of that file after uploading to minio. I see you've removed code to upload file to minio and that's not expected.

2020-09-26 04:43 UTC, belwase commented on gw_crawler/malicious_file_crawler/src/pipelines.py
> +            client.publish_job(payload)
Need error handling here if it got exception to publish

2020-09-26 04:44 UTC, belwase commented on gw_crawler/malicious_file_crawler/src/utils/rabbit_client.py
> +    MQ_USERNAME = environ.get("MQ_USERNAME", "guest")
Here Don't use default values on environ.get, See other modules on how config is used and an error is raised when variables are not set

2020-09-26 22:16 UTC, DinisCruz commented
Please address comments made by @belwase

2020-09-27 20:32 UTC, susilupwork requested changes
- It seems the task objective is diluted in implementation. You should be only touching MinIO code. There you will be calling RabbitMQ Handler endpoit to put S3 synchronization job. Another separate folder (K8 pod) should be there for your S3 synchronization. This will be called by Ashish, when job type is "S3 synch". Your pod will call MinIO URL get the zip file and push it to S3. 
- Minio to S3 Synchronization should be independent of other modules. It can not be inside gw_crawler folder.
- Do not put all possible variables in sample env file. Keep only the conventional  variables, and used in your code. It should be easier for people to install, typically sysadmin or QA team.
- pika.BlockingConnection method should not be used as it breaks the objective of Asynchronous architecture. Rather use SelectConnection . See https://stackoverflow.com/questions/11987838/which-form-of-connection-to-use-with-pika

2020-09-27 20:32 UTC, susilupwork commented on gw_crawler/.env_sample
> +MQ_VHOST=%2f
Minio to S3 Synchronization should be independent of other modules. It can not be inside gw_crawler folder.

2020-09-27 20:32 UTC, susilupwork commented on gw_crawler/.env_sample
> +MQ_CONNECTION_ATTEMPTS=3
Do not put all possible variables in sample env file. Keep only the conventional  variables, and used in your code. It should be easier for people to install, typically sysadmin or QA team.

2020-09-27 20:32 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/src/utils/rabbit_client.py
> +        self.connection = pika.BlockingConnection(pika.URLParameters(self.url))
pika.BlockingConnection method should not be used as it breaks the objective of Asynchronous architecture. Rather use SelectConnection . See https://stackoverflow.com/questions/11987838/which-form-of-connection-to-use-with-pika

2020-10-01 09:04 UTC, virajut commented
Have addressed the reviewer's comments and added it in #60 created new pull request.

2020-10-01 23:27 UTC, DinisCruz commented
@virajut is this PR still needed?

If so, where are your latest changes?

2020-10-02 03:43 UTC, belwase commented
This PR is not needed anymore. so marking as close

2020-10-02 03:43 UTC, closed without merging

2020-10-02 05:22 UTC, virajut commented
It is not needed @DinisCruz. Latest changes are in #60 .

2020-10-02 05:22 UTC, virajut commented
Thank you @belwase