Issues 84
k8-proxy/k8-test-data pull request #87
Opened 2020-10-15 11:10 UTC by samarthdd

Completed Issue -https://github.com/k8-proxy/k8-test-data/issues/84

Fetching files from minio

Zipping to .zip, .7z , .rar , .gz , .tar 

Storing in s3 bucket

Updated release notes

2020-10-15 11:52 UTC, susilupwork requested changes
- Get only the Glasswall approved file type as mentioned by Adam Sloman . https://glasswallsolutions.com/technology/
- 
- This is the 4th Minio Service client side code.  Rather create a util package where keep all client code. Call them in your respective modules. Same goes for S3 client python file.

2020-10-15 11:52 UTC, susilupwork commented on compressed_file_generator/main.py
> +                    if not object.split(".")[-1]=="zip":
Get only the Glasswall approved file type as mentioned by Adam Sloman .  https://glasswallsolutions.com/technology/

2020-10-15 11:52 UTC, susilupwork commented on compressed_file_generator/main.py
> +
Coding standard violation, too lengthy method. Break in to two or more functions.

2020-10-15 11:52 UTC, susilupwork commented on compressed_file_generator/src/utils/minio_service.py
> +import logging
This is the 4th Minio Service client side code.  Rather create a util package where keep all client code. Call them in your respective modules.

2020-10-15 11:52 UTC, susilupwork commented on compressed_file_generator/.env_sample
> +NUM_OF_FILES=100
Use .env file only for keys.

2020-10-16 06:41 UTC, samarthdd commented on compressed_file_generator/main.py
> +                    if not object.split(".")[-1]=="zip":
For time being keeping all formats as per Adam Sloman suggestion .

2020-10-16 06:42 UTC, samarthdd commented on compressed_file_generator/main.py
> +
I have changed this part and made it as 2 function call

2020-10-16 06:43 UTC, samarthdd commented on compressed_file_generator/.env_sample
> +NUM_OF_FILES=100
Removed PYTHONUNBUFFERED=

NUM_OF_FILES should come from user.So i have kept it in env

2020-10-16 06:46 UTC, samarthdd commented on compressed_file_generator/src/utils/minio_service.py
> +import logging
All Minio Service uses minio library and customise it according to project need

These are all custom code when I investigated all. In this particular case, i need to check types before proceeding furthur which is not the case in others

I have removed extra codes and keeping what is required

2020-10-19 20:29 UTC, susilupwork requested changes
Do not copy paste s3_client code for every microservice. Put it in gw.testdata.util  or some place. Use it as a library.  Or you need extra method update in library.  Same goes for Minio also.

2020-10-19 20:29 UTC, susilupwork commented on compressed_file_generator/src/utils/s3_client.py
> +import logging
Do not copy paste s3_client code for every microservice. Put it in gw.testdata.util  or some place. Use it as a library.  Or you need extra method update in library.  Same goes for Minio also.

2020-10-20 23:07 UTC, samarthdd commented on compressed_file_generator/main.py
> +                    if not object.split(".")[-1]=="zip":
I have removed minio and s3  service code and calling microservice

2020-10-21 10:52 UTC, susilupwork approved these changes
Looks good

2020-10-21 12:09 UTC, dtollaku approved these changes

2020-10-21 12:09 UTC, merged