Scrapyd batch processing
k8-proxy/k8-test-data pull request #95
Opened 2020-10-19 13:48 UTC by samarthdd

Implemented scrapyd

Implemented batch processing which will sync .scrapy cache to s3 bucket 

That .scrapy will be synched to s3 when scraper is stoped

It will be downloaded back from s3 when scraper starts to track files which are already downloaded

Fixed virustotal report issue

2020-10-19 20:49 UTC, susilupwork requested changes
Good comment done.
Do not copy paste Minio_service or s3_client code for every microservice. Put it in gw.testdata.util  or some place. Use it as a library.  Or you need extra method update in library.

2020-10-19 20:49 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/Dockerfile
> +
Why so many blank  lines. Use PyCharm to take care of formatting.

2020-10-19 20:49 UTC, susilupwork commented on compressed_file_generator/src/utils/minio_service.py
> +class MinioService:
Do not copy paste Minio_service or s3_client code for every microservice. Put it in gw.testdata.util  or some place. Use it as a library.  Or you need extra method update in library.

2020-10-19 20:49 UTC, susilupwork commented on gw_crawler/malicious_file_crawler/src/run_distributed_crawl.py
> +""" Main class for initializing and running crawlers. """
Good comment done.

2020-10-20 23:01 UTC, samarthdd commented on gw_crawler/malicious_file_crawler/Dockerfile
> +
Removed extra spaces

2020-10-20 23:01 UTC, samarthdd commented on compressed_file_generator/src/utils/minio_service.py
> +class MinioService:
Address this in PR : 102

2020-10-21 19:06 UTC, dtollaku approved these changes

2020-10-21 19:07 UTC, merged