Issue 89: Migrating gov-uk files from s3 and processing through k8-test-data file processor.
k8-proxy/k8-test-data pull request #97
Opened 2020-10-19 19:49 UTC by nirvishek

Process all gov_UK files from S3 bucket to generate metadata, rebuild XML and virustotal report.

2020-10-19 20:18 UTC, susilupwork requested changes
- Good commenting style. And Exception handling done. 
- You are downloading all files in one go. It is not scalable. You should have taken list of files, download one  and then process. Then jump to next file.
- Do not copy paste s3_client code for every microservice. Put it in gw.testdata.util  or some place. Use it as a library.  Or you need extra method update in library.

2020-10-19 20:18 UTC, susilupwork commented on gov_uk_file_migration/README.md
> +    `To build the Docker image and name it `multilevel-compression`
Why the name is multilevel

2020-10-19 20:18 UTC, susilupwork commented on gov_uk_file_migration/main.py
> +            list_files = self.s3.download_subdirectory_files(Config.S3_BUCKET, Config.S3_SUB_FOLDER_PREFIX,
You are downloading all files in one go. It is not scalable. You should have taken list of files, download one  and then process. Then jump to next file.

2020-10-19 20:18 UTC, susilupwork commented on gov_uk_file_migration/main.py
> +                # 3. upload the file to minio before passing it to processor.
Good commenting style.

2020-10-19 20:18 UTC, susilupwork commented on gov_uk_file_migration/src/utils/s3_client.py
> +import os
Do not copy paste s3_client code for every microservice. Put it in gw.testdata.util  or some place. Use it as a library.

2020-10-19 20:37 UTC, nirvishek commented on gov_uk_file_migration/README.md
> +    `To build the Docker image and name it `multilevel-compression`
I copied the readme from my previous module, updated the code now.

2020-10-20 01:39 UTC, nirvishek commented on gov_uk_file_migration/main.py
> +            list_files = self.s3.download_subdirectory_files(Config.S3_BUCKET, Config.S3_SUB_FOLDER_PREFIX,
I have refactored the code to fetch file iteratively one at a time with generator method, please review.

2020-10-20 23:58 UTC, nirvishek commented on gov_uk_file_migration/src/utils/s3_client.py
> +import os
I have moved the s3_client to storage service, and now calling its endpoint for s3 services.

2020-10-21 16:31 UTC, susilupwork approved these changes
Good to go.

2020-10-22 07:02 UTC, merged